---
- name: Simple playbook example
  hosts: server
  tasks:
    - name: Update the APT package cache
      apt:
        update_cache: yes

    - name: Install Git
      apt:
        name: git
        state: present

    - name: Print success message
      debug:
        msg: "Git has been installed successfully!"
